# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version = "10.0.2";
      src = {
        rev = "94c02dfc4a778a094cd8ad7b1d2348a96f024123";
        sha256 = "0bk86javsfm1mwlksnv8p7pws5ii3zag6aah13gn5zlc31z295yh";
      };
    };
    libVersion = {
      version = "10.0.2";
      libSources = {
        symbols.rev = "f31042c9759771f10754f02e54344dee750692b1";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "db5a3e2a99d5200cabfb03199fe28a5f3ba59191";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "c076368c29f8f5c3ad2ee7ed91083815b79ddb72";
        footprints.sha256 = "1h1v44qc5lvvqvmi1i7b79jhxsfq8snk0mcfl6r73hj6w0b25l84";
        packages3d.rev = "3720ad929a99187fc55a8d35895672ef9aaf9cb7";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version = "10.0-2026-05-09";
      src = {
        rev = "58a1e6556bf606cbc8da10733db8a9801cdfade3";
        sha256 = "1myln0iyl3z4s9h8867rr4zjka9xw04gdl29pqgj8ivjpm8gxw95";
      };
    };
    libVersion = {
      version = "10.0-2026-05-09";
      libSources = {
        symbols.rev = "f31042c9759771f10754f02e54344dee750692b1";
        symbols.sha256 = "05h8dbygch2kp4s5ikspxngwv999j7jwsiwm4pzwwcrir7dqzdfl";
        templates.rev = "db5a3e2a99d5200cabfb03199fe28a5f3ba59191";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "c076368c29f8f5c3ad2ee7ed91083815b79ddb72";
        footprints.sha256 = "1h1v44qc5lvvqvmi1i7b79jhxsfq8snk0mcfl6r73hj6w0b25l84";
        packages3d.rev = "3720ad929a99187fc55a8d35895672ef9aaf9cb7";
        packages3d.sha256 = "01nbjcs3890hyfmafc623ldmfi9n8sjr5m0wripz5fq5fjdnzqxl";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version = "2025-02-21";
      src = {
        rev = "878cf768d6552131494aa792dc20e6ccf67baf75";
        sha256 = "0ky0a7y6gf409y8bwpngiirqin4ivbcjnk8gjdj1a6w79x559sr8";
      };
    };
    libVersion = {
      version = "2025-02-21";
      libSources = {
        symbols.rev = "da86acd48809fd61876223c8bf0e4e7793c52e9a";
        symbols.sha256 = "1sdpg58wbyyrghjd0jqw5iw2094mjy2v9jmwn5zrj4jm6f51g1kd";
        templates.rev = "3ed4538b0f965d821df63a5fffc4441e723cfe7f";
        templates.sha256 = "0zs29zn8qjgxv0w1vyr8yxmj02m8752zagn4vcraqgik46dwg2id";
        footprints.rev = "e515f1c3213317d436e492c8c06620ef4caca84e";
        footprints.sha256 = "16zslgvjg4swgkkvnd9fmiks3wzg63364d03hixiyzcpjlgk2bbk";
        packages3d.rev = "d5db5cea003fe2b4b1c9b145f5fcbd5fdb48f8ca";
        packages3d.sha256 = "0bg54lg1iw01gw06ajg34y7x4y36wm6ls3jnpjy13i18d4ik77g4";
      };
    };
  };
}
